options:
  formatter: stylish
files:
  include: 'src/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 0
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    -
      convention: camelcase
      convention-explanation: 'Use camelcase for CSS Modules: `styles.someClassName`.'
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  bem-depth: 0
  border-zero: 1
  brace-style:
    - 1
    -
      style: stroustrup
      allow-single-line: true
  clean-import-paths: 0
  empty-args: 1
  hex-length:
    - 1
    -
      style: long
  hex-notation:
    - 1
    -
      style: lowercase
  indentation: 1
  # https://sass-guidelin.es/#zeros
  leading-zero:
    - 1
    -
      include: true
  nesting-depth:
    - 1
    -
      max-depth: 3
  property-sort-order:
    - 1
    -
      order:
        - '-webkit-appearance'
        - '-moz-appearance'
        - 'appearance'
        - 'content'

        # Position

        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'
        - 'z-index'

        # flexbox for items
        - 'flex'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-basis'
        - 'align-self'
        - 'order'

        # Box

        - 'display'
        - 'vertical-align'
        - 'table-layout'
        - 'border-collapse'
        - 'border-spacing'
        - 'box-sizing'

        - 'float'
        - 'clear'

        # flexbox for containers
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-wrap'
        - 'align-content'
        - 'align-items'
        - 'justify-content'

        - 'overflow'
        - 'overflow-x'
        - 'overflow-y'

        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'

        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'

        - 'border'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-width'
        - 'border-top-width'
        - 'border-right-width'
        - 'border-bottom-width'
        - 'border-left-width'

        - 'border-style'
        - 'border-top-style'
        - 'border-right-style'
        - 'border-bottom-style'
        - 'border-left-style'

        - 'border-radius'
        - 'border-top-left-radius'
        - 'border-top-right-radius'
        - 'border-bottom-left-radius'
        - 'border-bottom-right-radius'

        - 'border-color'
        - 'border-top-color'
        - 'border-right-color'
        - 'border-bottom-color'
        - 'border-left-color'

        - 'width'
        - 'min-width'
        - 'max-width'

        - 'height'
        - 'min-height'
        - 'max-height'

        - 'columns'
        - 'column-count'
        - 'column-gap'
        - 'column-width'
        - 'column-fill'
        - 'column-rule'
        - 'column-span'

        # Background

        - 'background'
        - 'background-attachment'
        - 'background-clip'
        - 'background-color'
        - 'background-image'
        - 'background-repeat'
        - 'background-position'
        - 'background-size'

        # SVG

        - 'fill'
        - 'stroke'
        - 'stroke-width'
        - 'stroke-miterlimit'
        - 'stroke-dasharray'
        - 'stroke-dashoffset'
        - 'stroke-linecap'
        - 'stroke-linejoin'

        # Text

        - 'color'

        - 'font'
        - 'font-family'
        - 'font-style'
        - 'font-variant'
        - 'font-weight'
        - 'font-size'
        - 'font-smoothing'

        - 'line-height'

        - 'letter-spacing'
        - 'list-style'

        - 'text-align'
        - 'text-decoration'
        - 'text-indent'
        - 'text-overflow'
        - 'text-rendering'
        - 'text-shadow'
        - 'text-transform'
        - 'text-wrap'

        - 'white-space'
        - 'word-spacing'

        # Outline

        - 'outline'
        - 'outline-color'
        - 'outline-offset'
        - 'outline-style'
        - 'outline-width'

        # Paint

        - 'visibility'
        - 'opacity'
        - 'box-shadow'

        # Transform

        - 'transform'
        - 'transform-box'
        - 'transform-origin'
        - 'transform-style'

        # Transition

        - 'transition'
        - 'transition-property'
        - 'transition-duration'
        - 'transition-delay'
        - 'transition-timing-function'

        # Animation

        - 'animation'
        - 'animation-name'
        - 'animation-duration'
        - 'animation-timing-function'
        - 'animation-delay'
        - 'animation-iteration-count'
        - 'animation-direction'
        - 'animation-fill-mode'
        - 'animation-play-state'

        # Other

        - 'caption-side'
        - 'cursor'
        - 'empty-cells'
        - 'quotes'
        - 'speak'
  quotes: 0
  shorthand-values: 0
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1